In [1]:
import torch

from arithmetic_lm.train_utils import insert_pause_tokens

In [2]:
a = torch.tensor(
    [
        [1, 1, 1.0, 0, 0],
        [1, 3, 5.0, 5, 5],
        [0, 0, 0, 0, 0],
    ]
)

insert_pause_tokens(
    a,
    pause_token_id=100,
    n_pause_tokens=3,
)

{0, 2, 3}
tensor([-1,  0,  1, -1,  2, -1,  3,  4])
tensor([[0., 1., 1., 0., 1., 0., 0., 0.],
        [5., 1., 3., 5., 5., 5., 5., 5.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[100.,   1.,   1., 100.,   1., 100.,   0.,   0.],
        [100.,   1.,   3., 100.,   5., 100.,   5.,   5.],
        [100.,   0.,   0., 100.,   0., 100.,   0.,   0.]])


tensor([[100.,   1.,   1., 100.,   1., 100.,   0.,   0.],
        [100.,   1.,   3., 100.,   5., 100.,   5.,   5.],
        [100.,   0.,   0., 100.,   0., 100.,   0.,   0.]])